name    'inkblot/openvpn'
version '0.0.1'
source  'git://github.com/inkblot/puppet-openvpn.git'
author  'inkblot'
license 'Apache 2.0'
summary 'OpenVPN SSL/TLS based VPN'
description 'A Puppet module to install and configure a OpenVPN'
project_page 'https://github.com/inkblot/puppet-openvpn'

dependency 'ripienaar/module_data', '>= 0.0.1'
